version: '3.2'
services:
  ember:
    image: danlynn/ember-cli
    entrypoint: ['ember']
    command: '-v'
    volumes:
      - type: 'bind'
        source: ./borrowers
        target: /myapp
  api:
    build:
      context: ./borrowerapi
    working_dir: /opt/app
    command: rails s -p 3000 -b 0.0.0.0
    ports: 
      - "3000:3000"
    volumes:
      - type: bind
        source: ./borrowerapi
        target: /opt/app
  rake:
    image: borrowerapi_api:latest
    entrypoint: rake 
    command: '-T'
    volumes:
      - type: bind
        source: C:/Users/chengyil/code/ember/borrowerapi
        target: /opt/app
  rails:
    image: borrowerapi_api:latest
    entrypoint: rails 
    command: '-v'
    volumes:
      - type: bind
        source: C:/Users/chengyil/code/ember/borrowerapi
        target: /opt/app
  irb:
    image: borrowerapi_api:latest
    entrypoint: irb 
    volumes:
      - type: bind
        source: C:/Users/chengyil/code/ember/borrowerapi
        target: /opt/app
  gem:
    image: borrowerapi_api:latest
    entrypoint: gem 
    command: '-v'
    volumes:
      - type: bind
        source: C:/Users/chengyil/code/ember/borrowerapi
        target: /opt/app
